### PR TITLE
Add tabler-react repository link to README

### PR DESCRIPTION
**Pull request by AaronCoplan**
We should make people aware of the SPA versions of tabler so they don't waste time re-implementing them themselves.  [tabler-react](https://github.com/tabler/tabler-react) seems to be the only one that is actively maintained at the moment, so I am adding that one in two places to the readme.

@codecalm Let me know your thoughts on this change!

### CODE REVIEW

**Comment by bravo-kernel** [comment]
There is an Ember SPA available as well starting today. It would be nice to mention them in e.g. a list or something. https://github.com/alt3/ember-tabler

**Comment by AaronCoplan** [comment]
@codecalm Is there any update on this?  It seems the tabler repository has had no activity in a while - the last commit was August 27...

**Comment by AaronCoplan** [comment]
@bravo-kernel I would gladly add them to the list in this PR however I accidentally deleted my fork of this repository when cleaning up my GitHub which is why it says `unknown repository` :(

**Comment by bravo-kernel** [comment]
Interesting, no way of closing this pull request via github interface?

**Pull request merged**
