### PR TITLE
#1513 issue:updated css varible without value in popover.

### PR DESCRIPTION
**Pull request by Nitz2611**

### CODE REVIEW

**Comment by kevinpapst** [comment]
You edited the files in `dist/` and `demo/dist/` directory. Your changes would be overwritten on the next build. Please apply your changes in the source files instead.

**Comment by Nitz2611** [comment]
@kevinpapst there is no tabler.css in source file. but in issue it says --tblr-popover-header-color variable is without value in [tabler/dist/css/tabler.css]

**Comment by kevinpapst** [comment]
I assume that this is a (new) bootstrap variable that needs to be defined.
Search for `$popover-header-color` in `node_modules/bootstrap/scss/_variables.scss`

The relevant parts are:
```
$headings-color:              null !default;
$popover-header-color:              $headings-color !default;
```

Interesting is, that even bootstrap itself seems to have that bug: 
Bildschirm­foto 2023-05-01 um 14 23 01

No clue what to do though

**Comment by Nitz2611** [comment]
So basically it is bootstrap bug. There is nothing we can do about it. Right?

**Comment by kevinpapst** [comment]
Initializing the variable with null looks like a bootstrap issue, yes.
Better if @codecalm will have a look at that.

**Pull request closed without merging**
