### PR TITLE
Chat component

### PR DESCRIPTION
**Pull request by codecalm**

### CODE REVIEW

**Comment by kevinpapst** [comment]
I'd say: both chat partners can get the same bubble color in dark mode.
So in dark mode the class `.chat-message-bubble` could have a `background-color: transparent`. Current it is white on white and unreadable.

**Comment by codecalm** [comment]
@kevinpapst it's a draft at this moment :)

**Comment by kevinpapst** [comment]
Yeah, I assumed you knew that. But I use tabler in my app and plan to help with (at least) feedback in the future.

**Comment by oranyero** [comment]
When will the chat option be available?

**Comment by oranyero** [comment]
No update about the chat?

**Comment by codecalm** [comment]
I've rebuild chat component here: https://github.com/tabler/tabler/pull/1636

**Pull request closed without merging**
