### PR TITLE
Resolved light dropdown issue on dark theme

### LINKED ISSUE #1603: Dark navbar but light dropdowns
### Discussed in https://github.com/tabler/tabler/discussions/1601

<div type='discussions-op-text'>

<sup>Originally posted by **mholt** May 15, 2023</sup>
Is it possible to restore the pre-beta-18 look of having a dark navbar but a light dropdown?

(Sorry I don't have a screenshot handy, switching back a version would be a bit tedious for me at the moment -- case of the Mondays I guess)

But hopefully the demo page can illustrate: https://preview.tabler.io/layout-navbar-dark.html

The dark navbar is useful for contrast, but on a light theme I want light dropdowns coming from that navbar. (Click on the profile info or notification bell for example)

Is it possible to restore that look (maybe with a CSS class or HTML attribute or something)?</div>

### PR DESCRIPTION
**Pull request by codecalm**
fixes #1603

### CODE REVIEW

**Comment by mholt** [comment]
Awesome!

To clarify: In light mode, a dark navbar will have light dropdowns? And in dark mode, a dark navbar will have dark dropdowns?

Basically the dropdowns should follow the theme, not the navbar. (Like it did before.)

Thank you!!

**Comment by kevinpapst** [comment]
Even better if we could style the dropdown manually with `<div class="dropdown..." data-bs-theme="dark"..>`

**Comment by codecalm** [comment]
@mholt @kevinpapst fixed 🙂

**Comment by mholt** [comment]
Thank you! Excited to try it.

**Comment by mholt** [comment]
Is the Preview link above by the Vercel bot supposed to show this change? https://tabler-git-dev-dropdown-light-fix-tabler-io.vercel.app/layout-navbar-overlap.html -- because this does not appear to have the light dropdowns...

**Comment by mholt** [comment]
@codecalm Just a reminder, I don't think this is actually fixed yet. Dropdowns are still dark even though theme is light: https://preview.tabler.io/layout-navbar-overlap.html?theme=light

**Pull request merged**
