### PR TITLE
New Chat component

### PR DESCRIPTION
**Pull request by codecalm**
Screenshot 2023-06-22 at 01 58 34

### CODE REVIEW

**Comment by mholt** [comment]
This looks very nice!

**Comment by kevinpapst** [comment]
Chat looks great, happy to see it merged.
But the demo file lives in `_includes`, is it even available through any navigation entry @codecalm ?

**Comment by codecalm** [comment]
yeah, i see, give me a minute

**Comment by codecalm** [comment]
@kevinpapst done: https://dev.tabler.io/chat.html 🙂

**Comment by kevinpapst** [comment]
Thanks ❤️

**Pull request merged**
