### PR TITLE
Nav overflow on Vertical Layout #1149 resolved

### PR DESCRIPTION
**Pull request by AlessandroGuelpa**
Hi!
I think that i solved the problem {[BUG] Nav overflow on Vertical Layout #1149}, let me know.

best reguards,
Alessandro.

### CODE REVIEW

**Comment by AlessandroGuelpa** [comment]
@rjd22 I think that both of the solution can solve this problem.
Looking both previews they do the same fix.

**Comment by gladtoseeugo** [comment]
UNSCRIBE

**Comment by rjd22** [comment]
Other solution was merged

**Comment by gladtoseeugo** [comment]
UNSCRIBE 



From: "Robert UNSCRIBE 

-Jan de Dreu" ***@***.***> 
To: "tabler" ***@***.***> 
Cc: "Sheila Jordan" ***@***.***>, "Comment" ***@***.***> 
Sent: Wednesday, August 3, 2022 4:20:26 AM 
Subject: Re: [tabler/tabler] Nav overflow on Vertical Layout #1149 resolved (PR #1155) 





Closed [ https://github.com/tabler/tabler/pull/1155 | #1155 ] .

**Pull request closed without merging**
