### PR TITLE
Inter iconfont

### PR DESCRIPTION
**Pull request by codecalm**

### CODE REVIEW

**Comment by kevinpapst** [comment]
There was a reason why we removed it: https://github.com/tabler/tabler/pull/1048

Can you make this a variable that can be overwritten by implementations? I am very happy with system default fonts. Wouldn't it cause the same bugs (e.g. [here](https://github.com/tabler/tabler/issues/1028)) as before, if someone has Inter installed?

**Comment by codecalm** [comment]
I've removed Inter font from CSS and override it in HTML. Now everything should be fine :)

**Comment by kevinpapst** [comment]
That looks like a great solution and example who to integrate custom fonts 👍

**Comment by kevinpapst** [comment]
And I do not see the capital `A` issue anymore:
Bildschirmfoto 2022-08-05 um 12 19 54

**Pull request merged**
