### PR TITLE
New statuses

### PR DESCRIPTION
**Pull request by codecalm**
localhost_3000_docs_statuses html_theme=light

### CODE REVIEW

**Comment by kevinpapst** [comment]
Nice ones 👍 

One question: couldn't you re-use [all existing bg-* colors classes](https://preview.tabler.io/docs/colors.html) instead of creating new ones?

Are PRs/branches auto-deployed somewhere so we can have a look without building locally?

**Comment by codecalm** [comment]
@kevinpapst its not possible to use `bg-*` classes, because I need rgba color values :( 

you can view preview here: https://deploy-preview-965--tabler.netlify.app/ :)

**Comment by kevinpapst** [comment]
All "normal" ones look exactly the same with the bg-* classes, only some of the animated ones look wrong when using bg-* classes. But yeah, you know what you are doing 😄 

Any idea why Indigo is wrapped on page load? Maybe this is a Safari bug, it doesn't happen on Firefox/Chrome. The spaces do not collapse as as well (which I have never seen before).
Bildschirmfoto 2021-12-17 um 01 32 48

**Review by rjd22 — APPROVED** [review]

**Comment by rjd22** [comment]
@codecalm do you like this enough to merge it? Or is it unfinished?

**Comment by codecalm** [comment]
@rjd22 I'll resolve conflicts and I'll merge it :)

**Pull request merged**
