### PR TITLE
Navbar unify

### PR DESCRIPTION
**Pull request by codecalm**

### CODE REVIEW

**Comment by kevinpapst** [comment]
You know what I'd love to see: 
some kind of pointer, that helps to quickly identify possible BC breaks, so it is easier to find out what needs to be changed by every Tabler user upon update.
Maybe a Label? Or a flag in the changelogs files, so it appears in the GitHub release notes?

**Comment by codecalm** [comment]
@kevinpapst okay, I'll add it to docs 🙂

**Comment by kevinpapst** [comment]
Thank you so much, and thanks for all the love/work/time you put into Tabler!

**Comment by kevinpapst** [comment]
Latest Vercel deployment looks broken @codecalm :
Bildschirmfoto 2023-06-07 um 21 15 33

**Pull request merged**
