### PR TITLE
Unify dark mode with latest Bootstrap API and improve dark mode elements

### PR DESCRIPTION
**Pull request by codecalm**
This PR unifies the dark mode in our project with the latest Bootstrap API and improves the design and functionality of dark mode elements. The updated dark mode provides a more consistent and polished user experience across our application.

### CODE REVIEW

**Comment by kevinpapst** [comment]
At first glance: better than before. 
Only thing I noticed in a couple of minutes browsing: the parent of sub-menus is not highlighted anymore, e.g "Layout" should be underlined [here](https://tabler-git-dev-bootstrap-dark-mode-tabler-io.vercel.app/layout-navbar-sticky.html).

**Comment by codecalm** [comment]
@kevinpapst good, I'm fixing it. If you have any other bugs give me know

**Comment by mholt** [comment]
I was using `.theme-dark-auto` -- what do you recommend as a replacement?

**Comment by xvilo** [comment]
As @mholt asked before, what is currently a replacement or alternative to the `.theme-dark-auto`. This has, unfortunately, been removed with this PR. 

@codecalm are able to give us some guidance regarding the old class?

**Pull request merged**
