### PR TITLE
Upgrade bootstrap to 4.3

### PR DESCRIPTION
**Pull request by pmccarren**
Upgrade bootstrap to 4.3

Refer to the Bootstrap [Release Notes](https://blog.getbootstrap.com/2019/02/11/bootstrap-4-3-0/) for details.

### CODE REVIEW

**Comment by WinterSilence** [comment]
current version is 4.3.1 https://github.com/twbs/bootstrap/releases

**Comment by mchobbylong** [comment]
So weird that this PR is not merged after a month...

New features such as "Toasts" in Bootstrap v4.3 are nice. Wonder the reason why the CSS of Bootstrap v4.3 was upgraded in `/dist` but the JS was not.

**Comment by WinterSilence** [comment]
@mchobbylong main thing is bug/secure fixes

**Comment by dsznajder** [comment]
@pmccarren Thanks for this one. We are currently working on `v1` version with the newest bootstrap. Feel free to try it from the main branch or stay tuned for the release!

**Pull request closed without merging**
