### PR TITLE
#1456 Fixed paths to bootstrap scss files

### PR DESCRIPTION
**Pull request by kicaj**

### CODE REVIEW

**Comment by kevinpapst** [comment]
This is a duplicate of #1333 with a slightly different approach

**Comment by rjd22** [comment]
@kevinpapst this feels like the correct approach with the node_modules folder excluded. This way you leave figuring out the location to your builder AFAIK?

**Comment by kevinpapst** [comment]
I'd say so too, at least I have never seen a setup with `node_modules/` in the import/require statement.

**Comment by rjd22** [comment]
Since the build is failing I want to make sure. @codecalm could you check if this is the right way? I get the weird underbelly feeling that it should be `@bootstrap` to make this work properly cross platform.

**Comment by kevinpapst** [comment]
Isn't the @ used in case the package is scoped, which bootstrap isn't? Maybe I am totally wrong here 🤷

**Comment by rjd22** [comment]
> Isn't the @ used in case the package is scoped, which bootstrap isn't? Maybe I am totally wrong here shrug

Ah, you're completely right. I thought bootstrap was scoped. But after checking it seems it isn't.

**Comment by kicaj** [comment]
Everything will be better then that  `../../`

**Comment by codecalm** [comment]
what if we copy bootstrap files to `scss` directory instead use it as dependency?

**Comment by kicaj** [comment]
I thinks it is not good idea.

**Comment by SyntaxJoker** [comment]
This problem with imports appeared in many issues and PRs, I created a separate PR to address all of them
https://github.com/tabler/tabler/pull/1477

**Pull request closed without merging**
