### PR TITLE
tabs

### PR DESCRIPTION
**Pull request by mstfece**

### CODE REVIEW

**Review by kevinpapst — CHANGES_REQUESTED** [review]
Thanks for your contribution. Is that related to #1635 ?

This is a first review from my side. Tabler is based on Bootstrap, so you should base your component on of the Bootstrap components, e.g. 
- a button group: https://getbootstrap.com/docs/5.3/components/button-group/
- or a "tabbed" nabigation: https://getbootstrap.com/docs/5.3/components/navs-tabs/#tabs

So your need to adapt the code first and then style it, probably targeting with a new dedicated class.

Your styles should then go into one of the UI sass files: 
https://github.com/tabler/tabler/tree/dev/src/scss/ui

Maybe you can also share a screenshot?

**Comment by mstfece** [comment]
I understand. I'll edit the code and try again

**Comment by mstfece** [comment]
image
 my request look like this.

**Comment by kevinpapst** [comment]
So, this is not related to #1635 - understand.

Your changes do not make sense to me. 
Now all CSS changes are gone, super weird html tags...

```
<body>
</head>
```

If you want to commit to this project (or any project for that matter), you should add a description to your PR that explains what want to achieve with your code.

**Pull request closed without merging**
