### PR TITLE
New navigation refactor

### PR DESCRIPTION
**Pull request by codecalm**
- [x] vertical navbar
- [x] move to CSS Variables
- [x] collapsed navbar

### CODE REVIEW

**Comment by kevinpapst** [comment]
There is a bug. Now not only the buttons are unreadable #1177, but the entire navigation is "gone":
Bildschirmfoto 2022-09-18 um 10 55 56

**Comment by codecalm** [comment]
@kevinpapst there is still draft :) i'm working on it still

**Comment by kevinpapst** [comment]
Ok, give me a ping if you want someone to test it!

**Comment by ivalkenburg** [comment]
Only thing I noticed so far that the overflow is hidden on the new navigation bar in the vertical layouts. Other than that, it looks absolutely great. Cannot wait to implement it.

**Pull request closed without merging**
