### PR TITLE
Datatables

### PR DESCRIPTION
**Pull request by thiscodeworks**
Added working datatables with UI of tabler.

screen shot 2018-05-12 at 15 51 05

### CODE REVIEW

**Comment by bloggervista** [comment]
Can we remove jQuery ? I guess vanialla js is better at least we can change code to Vue or React easily :)

**Comment by thiscodeworks** [comment]
@bloggervista hey, jquery is already part of many plugins in Tabler .. idk if there is official vanilla datatables repo. I will add some other things like wysiwyg editor, datetimepicker etc. and try to push it in vanilla only.

**Comment by bloggervista** [comment]
@thiscodeworks  yea but I think we should go data centric way. 

But I have already been using this although it is not merge :)

Thanks 
👍

**Comment by thiscodeworks** [comment]
@bloggervista ok I will do my best in next plugins 😉.. I will push another datatables UI fix like missing arrows in table header for sorting, active item in breadcrumb, and more .. and push builded version too. Thanks!

**Comment by tiagocassio** [comment]
Any prediction when this will be merged?

**Comment by bloggervista** [comment]
Yeah I guess thiscodeworks has really done hard work and this needs to be reviewed :)

**Comment by AbbyJanke** [comment]
Would love to see this merged, I'm going to manually add it for now but would be great to be default.

For posterity's sake mentioning issue https://github.com/tabler/tabler/issues/72 which requests datatables.

**Comment by orkuncaylar** [comment]
I could not find it, but can you help me please?

**Comment by sercanarga** [comment]
@codecalm Merge...

**Comment by WiSo-UzK** [comment]
Is it still working? What do i have to do, to include working datatables with tabler?

**Pull request merged**
