### PR TITLE
update dependencies, update tabler icons to v1.72

### PR DESCRIPTION
**Pull request by codecalm**
fixes: #1168

### CODE REVIEW

**Review by rjd22 — APPROVED** [review]

**Comment by gladtoseeugo** [comment]
UNSCRIBE

**Comment by gladtoseeugo** [comment]
UNSCRIBE

**Comment by gladtoseeugo** [comment]
UNSCRIBE 


From: "Paweł Kuna" ***@***.***> 
To: "tabler" ***@***.***> 
Cc: "Subscribed" ***@***.***> 
Sent: Wednesday, August 3, 2022 4:01:18 AM 
Subject: [tabler/tabler] update dependencies, update tabler icons to v1.72 (PR #1182) 



fixes : [ https://github.com/tabler/tabler/issues/1168 | #1168 ] 
You can view, comment on, or merge this pull request online at: 


[ https://github.com/tabler/tabler/pull/1182 | https://github.com/tabler/tabler/pull/1182 ] Commit Summary 


    * [ https://github.com/tabler/tabler/pull/1182/commits/2438d6bd0d36a054ffff61c77835e0e8de6732f1 | 2438d6b ] update dependencies, update tabler icons to v1.72 
File Changes 


( [ https://github.com/tabler/tabler/pull/1182/files | 3 files ] ) 

    * M [ https://github.com/tabler/tabler/pull/1182/files#diff-053150b640a7ce75eff69d1a22cae7f0f94ad64ce9a855db544dda0929316519 | package-lock.json ] (5300) 
    * M [ https://github.com/tabler/tabler/pull/1182/files#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519 | package.json ] (48) 
    * M [ https://github.com/tabler/tabler/pull/1182/files#diff-6c6929237f6d43f343df640e864da2fe5389c767b70cea634c4143ce4922fded | src/pages/_data/icons.yml ] (801) 
Patch Links: 


    * [ https://github.com/tabler/tabler/pull/1182.patch | https://github.com/tabler/tabler/pull/1182.patch ] 
    * [ https://github.com/tabler/tabler/pull/1182.diff | https://github.com/tabler/tabler/pull/1182.diff ]

**Comment by gladtoseeugo** [comment]
UNSCRIBE

**Pull request merged**
