### PR TITLE
Fix some missing variables, minor tweaks to some colors

### LINKED ISSUE #1592: [BUG] Card header is too bright (lacks contrast)
**Describe the bug**

The card header is too close to white. In Tabler beta 17 it was a more legible color.

**Device**

 - Browser [e.g. Chrome ver.22, Safari ver.10] Firefox, Chrome, and Safari
 - OS: [e.g. Windows 10] Linux, and Mac
 - Screen size [e.g. 800x600] 5120x1440 and others

**To reproduce**

Basically just using the `--tblr-card-cap-bg` variable

**Screenshots**

image

I'm not sure if the lack of contrast is obvious on your screen, but on mine the two (`--tblr-card-cap-bg`, which evals to `--tblr-bg-surface-tertiary`, which is `--tblr-gray-50`, which is `#fcfdfe`; and `#fff`) are nearly identical. I was confused as to why my card headers suddenly became "white" but then I looked closely and it's actually a very very very very very light grey.

I wouldn't mind going back to whatever color Tabler beta 17 used, or at least something closer to it than white.

`#fcfdfe` is _extremely_ close to `#ffffff`, moreso than a variable named `--tblr-gray-50` would lead me to believe.

---

Thank you as always for Tabler, I'm happy to continue sponsoring. Really appreciate the work you're doing!

### PR DESCRIPTION
**Pull request by mholt**
This PR attempts to repair some of the broken variable names from the Bootstrap 5 transition somewhere between betas 16 and 19 (and now beta 20 as of this morning) and to improve the accessibility with a more visually consistent color-step palette.

(Apologies for my non-hi-DPI screen with which I took these screenshots...)

Border color on hover was black because of missing variable:

image

I restored the previous look by repairing the variable, which makes it a dark gray (which IMO looks better too -- this is the way it was in beta ~16):

image

Card caps bg is currently too hard to see:

image

Now it is visible again, closer to beta 16:

image

(Thus this PR fixes #1592)

It resolves a few accessibility issues as well:

- Hover BGs are now visible, they got lost somewhere between beta 16 and 19. Now they're even more visible, but not too much.
Before:
image
Current:
image
After:
image

- Restored the pre-beta-19 blue color, so that Tabler brand color is its own distinct color. This also improves contrast of buttons and links which are now more legible in dark mode.
Current:
image
After:
image

There's still some work to do which I may push to this PR if it's still open, but I think this PR is a good step forward and ready to go anyway.

(These visibility/accessibility improvements are required for my app, hence my PR. I'd love to not have to maintain a fork of Tabler, if it's possible I'd like to get this -- or something like this -- merged. :blush:)

### CODE REVIEW

**Comment by mholt** [comment]
I'm still trying to figure out how to bring back the beta 16 navbar link hover colors. In dark mode, the links were gray but become white on hover. I can't seem to figure out how to make that happen in beta 20?

**Comment by rjd22** [comment]
@codecalm What do you think of this? Imo looks good for me but maybe you have other ideas?

**Comment by kevinpapst** [comment]
Thanks @mholt for your work! Waiting for these fixes and a new release...

**Comment by mholt** [comment]
Thank you for merging :blush:

**Comment by mokazemi** [comment]
Hi. Just wanted to ask when there would be a new release so this hover issue is fixed?

**Pull request merged**
