### PR TITLE
Prevent deprecation warning for Angular 13 or higher

### PR DESCRIPTION
**Pull request by lvanstrijland**
I use tabler for my Angular project and since Angular i'm getting bombed with deprecation warnings when I try to compile my project because of the tilde that is used in the scss imports.

afbeelding

So I changed the way of importing from the node_modules folder.
Please let me know what you think about this approach.

Kind Regards,
Laurens van Strijland

### CODE REVIEW

**Comment by codecalm** [comment]
@lvanstrijland sorry, but after your changes Tabler won't compile:

```
Error in plugin "sass"
Message:
    src/scss/_config.scss
Error: Can't find stylesheet to import.
  ╷
1 │ @import "/node_modules/bootstrap/scss/functions";
  │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  ╵
  src/scss/_config.scss 1:9  @import
  src/scss/demo.scss 3:9     root stylesheet
  ```

**Comment by lvanstrijland** [comment]
@codecalm Thanks for your response, I will try to build it locally and resolve the errors, I will inform you when I updated the PR

**Comment by lvanstrijland** [comment]
@codecalm It looks like my new approach resolved the issue with compiler.
It still works as expected for both Angular and the project itself when I run `npm run start`

**Comment by codecalm** [comment]
thank you for help! :)

**Comment by SyntaxJoker** [comment]
This problem with imports appeared in many issues and PRs, I created a separate PR to address all of them
https://github.com/tabler/tabler/pull/1477

**Pull request closed without merging**
