### PR TITLE
Fixed global variable for `.card` and `.btn`

### PR DESCRIPTION
**Pull request by wangkanai**
Fixed global variable `--#{$prefix}card-bg` from `$dark` to `$dark-mode-dark`. This would also fixed the issue with .btn also, because it effect same underline when switching to dark theme.

image

### CODE REVIEW

**Comment by wangkanai** [comment]
I hope you like this fixed i have made for tabler. everything looks good to go now.

https://tabler-git-fork-wangkanai-card-tabler-ui.vercel.app/form-elements.html?theme=dark

image

**Comment by codecalm** [comment]
nice! can you resolve conflicts?

**Comment by wangkanai** [comment]
image

fixed the button issue

**Comment by wangkanai** [comment]
I think everything is ready for review and able to merge the PR now. @codecalm @rjd22

**Comment by rjd22** [comment]
@codecalm could you take a look?

**Comment by wangkanai** [comment]
@codecalm you do not my fixed? Do I need to change anything?

**Comment by codecalm** [comment]
@wangkanai cards has `#f8fafc` bg, instead of `#fff` - except it, everything looks fine! :)  

Screenshot 2022-09-11 at 16 02 42

**Comment by wangkanai** [comment]
I have the color of the card bg, please have a look.

**Comment by codecalm** [comment]
merged, thank you! :)

**Comment by wangkanai** [comment]
I'm happy to help out. 
If I find anything else, I keep droping new PR.

Bests,

Sarin

**Pull request merged**
