### PR TITLE
Security measure: fail PR if a lock file was changed

### PR DESCRIPTION
**Pull request by kevinpapst**
There were quite a lot of PRs in the past, which shipped changed **lock files**.

Those were mostly introduced by unexperienced contributors, but considering the popularity of Tabler and the amount of potential targets, this could be a real security risk:
https://snyk.io/blog/why-npm-lockfiles-can-be-a-security-blindspot-for-injecting-malicious-modules/

There is a simple way to prevent that, which I am using in all my projects: a workflow that checks the PR for changed lock files and fails directly if a changed lockfile was included. The only persons allowed to push changes for those files are @codecalm and @dependabot (see e.g. #1296).

The used workflow is: https://github.com/xalvarez/prevent-file-change-action

What do you think @codecalm about the idea in general?

~~This PR is a draft for now, because I am not sure about the required [token permissions](https://docs.github.com/en/actions/security-guides/automatic-token-authentication). I posted a question in the action repo and will update the workflow file accordingly if there are more required.~~

### CODE REVIEW

**Comment by kevinpapst** [comment]
Updated permissions according to https://github.com/xalvarez/prevent-file-change-action/pull/489

Ready for review.

**Comment by codecalm** [comment]
for me its good! ❤️

**Comment by kevinpapst** [comment]
Your project => you merge 😄

**Comment by codecalm** [comment]
take it 😂

**Comment by kevinpapst** [comment]
You called for it hahaha

**Comment by kevinpapst** [comment]
I don't quite understand why the merge run failed.

Can you merge dev into any branch that has a PR, so we can check if those fail as well.

**Comment by codecalm** [comment]
I'll merge https://github.com/tabler/tabler/pull/1350 in few minutes

**Comment by kevinpapst** [comment]
That worked. I guess that the action somehow has an issue when itself is merged into a new branch.
I'll take care if that happens again.

**Pull request merged**
