### PR TITLE
Revert active list item edge highlight

### PR DESCRIPTION
**Pull request by df2**
Keep it minimal

### CODE REVIEW

**Comment by rjd22** [comment]
@df2 can you share a screenshot on what this change does? That way it's easier for me to review.

**Comment by df2** [comment]
Sure @rjd22. After comparing the two again, I like it better with the edge highlight. What do you think?

With edge highlight (current code):
Screenshot_20220324_195938

Without edge highlight:
Screenshot_20220324_195856

**Comment by rjd22** [comment]
Yep, I would not remove the edge highlight. Is it okay to close this PR in that case?

**Comment by df2** [comment]
Absolutely. Will close it with this comment. I sent in another pull request (#1100) with a refactor of the properties of the highlight css that that's just a cleaner way to do it.

**Pull request closed without merging**
