### PR TITLE
Replace `!important` modifier with more specific selectors ...

### PR DESCRIPTION
**Pull request by df2**
… and also replace hard coded border width with `$border-width-wide` variable.

### CODE REVIEW

**Comment by rjd22** [comment]
I'm leaving this one for @codecalm I don't mind but since this is more of a style change maybe @codecalm has a opinion in this.

**Comment by df2** [comment]
Sounds good @rjd22. I haven't tested it but it should also make it easier for rtl styles to move the highlight to the right.

**Comment by df2** [comment]
RTL style works fine with it 👍

Arabic example:
Screenshot_20220325_081255

**Comment by codecalm** [comment]
thank you for help! :)

**Pull request merged**
