### PR TITLE
Replace .page-center with .my-auto in single page layouts

### LINKED ISSUE #1820: [BUG] Terms of Service demo page is cut off
### Browser

Chrome 120

### OS

Win 10

### Screen size

1920x1080

### Describe the bug

The top side of the page https://preview.tabler.io/terms-of-service.html is cut off (item 1 is not visible at all)

### How to reproduce

1. Go to https://preview.tabler.io/terms-of-service.html
2. top of the page is missing, article 1 not visible

### Screenshots

_No response_

### JSFiddle

_No response_

### PR DESCRIPTION
**Pull request by srsbiz**
Fixes #1820

### CODE REVIEW

**Comment by codecalm** [comment]
can you replace also in `_layouts/error.html`?

**Comment by wtsvishal** [comment]
my-auto is not working but page-center is still working. so please check once.

**Comment by srsbiz** [comment]
> my-auto is not working but page-center is still working. so please check once.
What exactly is not working? Please provide more details, like URL to broken page in [preview.tabler.io](https://preview.tabler.io), screen with marked area that is wrong, your browser and screen resolution.

**Comment by wtsvishal** [comment]
let's say we have open login page which should display as center of the page but due to add my-auto is used so my-auto does not work somehow but page-center instead of my-auto is working. same this happen in page-loader too.

**Comment by srsbiz** [comment]
It is centered on all major browsers - Chrome, MS Edge, Opera, FireFox 

image

Unless you provide more info about your enviroment it's hard to find any solution

**Comment by wtsvishal** [comment]
No it is not vertical center and I am using latest google chrome and I
noticed in your share screenshot your browser height is too small. I am
using mac and in that it is aligned top not centered. Let me know if you
still need more information.
<https://www.wingstechsolutions.com/>   Vishal GelaniSr. Full Stack
Developer
***@***.***
wingstechsolutions.com <https://www.wingstechsolutions.com/>

**Comment by srsbiz** [comment]
Well, the whole purpose of this change is to sacrifice vertical alignment since it does not work well with larger content.

`.page-center` class is stil available for use, but keep in mind that should be used only for very small content

**Comment by wtsvishal** [comment]
Gotcha.
<https://www.wingstechsolutions.com/>   Vishal GelaniSr. Full Stack
Developer
***@***.***
wingstechsolutions.com <https://www.wingstechsolutions.com/>

**Comment by carlosmintfan** [comment]
@wtsvishal #2114 fixes this.

**Comment by wtsvishal** [comment]
Awesome, thanks!
<https://www.wingstechsolutions.com/>   Vishal GelaniSr. Full Stack
Developer
***@***.***
wingstechsolutions.com <https://www.wingstechsolutions.com/>

**Pull request merged**
