### PR TITLE
Add variables for asset paths

### PR DESCRIPTION
**Pull request by beeman**
## Description

This PR adds some variables so the path to the assets can be set when using the scss in another project. 

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### CODE REVIEW

**Comment by ollym** [comment]
I don't think you should do it this way.

You should have a function like `tblr_asset_path` which resolves the asset path. You could then override this function so this can be used with a package manager for example Sprockets in Rails or provide a custom base path.

**Comment by beeman** [comment]
Hey @ollym, thanks for your input. I've simply copied how settings paths works in FontAwesome.

Feel free to send a PR with how you think it can be implemented easier.  

I would like to aim for the simplest implementation possible. Can you show an example of how your suggestion would work?

**Comment by digilist** [comment]
I would really like to see this feature merged.

@ollym can you provide an example? I've never seen an asset path configuration with a function, only with variables like @beeman did it.

**Comment by yatsyk** [comment]
> Hi guys, any way to merge it? It's impossible to add tabler to existing project via SCSS :(

As this pull request is not merged yet you can use tabler from fixed repo:

`npm install https://github.com/beeman/tabler.git#beeman/variable-asset-path --save`

```
//style.scss in your project
$tabler-base: "../node_modules/tabler-ui/src/assets";
@import '../node_modules/tabler-ui/src/assets/scss/variables';

//your changes 

@import '../node_modules/tabler-ui/src/assets/scss/dashboard/bootstrap/bootstrap';
@import '../node_modules/tabler-ui/src/assets/scss/dashboard/dashboard';
```

**Pull request closed without merging**
