### PR TITLE
Fix text color in dark version of navbar

### LINKED ISSUE #1568: [BUG] Beta 18 - Dark navbars are broken
**Describe the bug**

I guess you see the problems yourself in the screenshots.
Switching to dark mode, everything works fine ... but when only the navbars are dark, the link/button colors are off

https://preview.tabler.io/layout-navbar-overlap.html
Bildschirmfoto 2023-05-14 um 20 10 55

https://preview.tabler.io/layout-navbar-dark.html
Bildschirmfoto 2023-05-14 um 20 06 54

https://preview.tabler.io/layout-vertical.html
Bildschirmfoto 2023-05-14 um 20 07 40

### PR DESCRIPTION
**Pull request by codecalm**
fixes #1568

### CODE REVIEW

**Comment by kevinpapst** [comment]
such a tiny change, such a chnage. looks good now 👍

**Comment by codecalm** [comment]
@kevinpapst I don't know why I haven't seen this before 🫣

**Comment by kevinpapst** [comment]
Sorry for not testing earlier 😢 
I guess I will post some more smaller issues about the dark mode. 

I am currently implementing the changes in my "symfony tabler bundle" and in my app.
Do I have to add the `data-bs-theme="dark"` in the navbars or is it still `navbar-dark` class?

**Comment by codecalm** [comment]
Bootstrap will remove `navbar-dark` in next release so I unify it with Tabler

**Review by kevinpapst — APPROVED** [review]
LGTM and all test cases work now 👍

**Pull request merged**
