### PR TITLE
Add icon pulse/tada/rotate animations

### PR DESCRIPTION
**Pull request by dheineman**
Adds the icon animation classes from [tabler-icons.io](https://tabler-icons.io/) to tabler itself so everyone can use them.

fixes: https://github.com/tabler/tabler/issues/974

### CODE REVIEW

**Comment by kevinpapst** [comment]
I gave it a try with FA and it works as well. I like the animations, just wondering if that shouldn't be part of a dedicated icon library instead? But I guess that's a philosophical question that nobody can ultimately answer 😁

**Comment by dheineman** [comment]
I figured if you want to provide a large number of different animations you could move to a separate library. But for just three of them i think it is a nice little addition to tabler itself.

**Comment by gladtoseeugo** [comment]
UNSCRIBE

**Comment by gladtoseeugo** [comment]
UNSCRIBE 


From: "Dave Heineman" ***@***.***> 
To: "tabler" ***@***.***> 
Cc: "Subscribed" ***@***.***> 
Sent: Thursday, August 4, 2022 2:40:04 AM 
Subject: [tabler/tabler] Add icon pulse/tada/rotate animations (PR #1183) 



Adds the icon animation classes from [ https://tabler-icons.io/ | tabler-icons.io ] to tabler itself so everyone can use them. 

fixes : [ https://github.com/tabler/tabler/issues/974 | #974 ] 
You can view, comment on, or merge this pull request online at: 


[ https://github.com/tabler/tabler/pull/1183 | https://github.com/tabler/tabler/pull/1183 ] Commit Summary 


    * [ https://github.com/tabler/tabler/pull/1183/commits/ce5543acb3e0f30b7bd44970656e653777ca0a38 | ce5543a ] Add icon pulse/tada/rotate animations 
File Changes 


( [ https://github.com/tabler/tabler/pull/1183/files | 2 files ] ) 

    * M [ https://github.com/tabler/tabler/pull/1183/files#diff-9be69dbe1e50185ef58234abac1a3c54b55cd33cdc131684b5419531fff68818 | src/pages/_docs/icons.md ] (7) 
    * M [ https://github.com/tabler/tabler/pull/1183/files#diff-f18566e19244d49db0785a09e2d673eed8ffa357a967a10649095a933402431a | src/scss/ui/_icons.scss ] (60) 
Patch Links: 


    * [ https://github.com/tabler/tabler/pull/1183.patch | https://github.com/tabler/tabler/pull/1183.patch ] 
    * [ https://github.com/tabler/tabler/pull/1183.diff | https://github.com/tabler/tabler/pull/1183.diff ]

**Pull request merged**
