### PR TITLE
New docs

### PR DESCRIPTION
**Pull request by codecalm**
preview: https://tabler.io/docs/

Screenshot 2023-02-27 at 01 09 04

### CODE REVIEW

**Comment by kevinpapst** [comment]
I'd like to repeat my feedback (I know you might not like it and you are the maintainer, sorry in advance) ... but:
the link "Documentation" from the main menu now points to Github is useless => should be fixed..
Bildschirm­foto 2023-02-27 um 12 34 12

Rendering docs via Next.js and not with your own theme => I still don't get it at all. 
Why don't we improve together the documentation layout, instead of using a foreign one? 
What is the reasoning of not using Tabler? To me that feels almost like betraying your own project 😁 

Btw: the "preview boxes" are all cutting off content, like here: https://tabler.io/docs/components/timelines

**Comment by codecalm** [comment]
@kevinpapst 

I want to separate the documentation from the preview. A lot of people download the tabler to their computer and we are already losing them. One documentation in one place will increase traffic to markting sites. I am now looking for investors who would like to put money into the project and let's not kid ourselves, the number of users is one of the main arguments

Secondly, I am working on a tabler for marketing pages and would like to eventually use it on tabler.io, in which case our own framework would still be used.

Another argument is that I would like to work hard on the documentation. Add a search engine in the future, the possibility to preview snippets live, a live editor, etc. This is unfortunately not possible in Jekyll, without using any frontend framework. I want the tabler to be mage light and fast, without a ton of rarely used code.

And I am planning, together with @SyntaxJoker, to add the official frameworks for react and vue, so using them in next.js will still be using our own framework :) 

I know there is still some work to be done on the documentation, but I wanted it to already start being indexed by search engines, etc. :)

**Comment by kevinpapst** [comment]
I understand the wish for better SEO results. Moving docs to the main page would also work with your Tabler. 😄 

> I am now looking for investors who would like to put money into the project 

Please don't go the AdminLTE way, which just made the entire project go to shit. 
I am sure companies would invest their share (I would).
But the progress needs to be more constant and it is really time for stabilisation and 1.0.

**Comment by codecalm** [comment]
Yeah, sure. But without investors, I cannot devote 100% of my time to development. The decoupling of the documentation was one of the things that version 1.0 was waiting for. We fixed a lot of bugs, in fact only cosmetic things are left.

**Pull request merged**
