### PR TITLE
Responsive pricing cards fix  for all devices.

### PR DESCRIPTION
**Pull request by sushant1221**
Responsive pricing cards fixes as mentioned in

[https://github.com/tabler/tabler/issues/60](url)

### CODE REVIEW

**Comment by codecalm** [comment]
hi @sushant1221
`dist/` dir is generated by script, so every changes inside it will be overriden. Please make this fix inside `src/plans.html` :)

**Comment by codecalm** [comment]
fixed

**Comment by sushant1221** [comment]
Hey codecalm. I couldn't find plan.html file in SRC? Where is it?

**Comment by codecalm** [comment]
@sushant1221 I mean `pricing-cards.html`. Sorry for misspelled.

**Pull request closed without merging**
