### PR TITLE
Release version 1.0-beta18

### PR DESCRIPTION
**Pull request by codecalm**
Preview: https://dev.tabler.io/

### CODE REVIEW

**Comment by rjd22** [comment]
@codecalm I'm not going to review that xD

**Comment by kevinpapst** [comment]
That broke Tomselect dropdown in dark mode:
Bildschirm­foto 2023-03-16 um 23 00 45

Bildschirm­foto 2023-03-16 um 23 01 34

I think we need some dark-mode adjustments like I mentioned in https://github.com/tabler/tabler/pull/1508#issuecomment-1472086129 - but mine are not Tabler compliant, just a backend dev trying to do frontend tasks 😁

**Comment by codecalm** [comment]
fixed! :) 

Screenshot 2023-03-16 at 23 09 55

**Comment by kevinpapst** [comment]
Your 3 lines compared to my weird code 👍 Every time I see your commits, I know why I am not submitting PRs to Tabler^^

**Comment by kevinpapst** [comment]
BTW: the vercel deployment is broken, I guess because bundlewatch failed.

**Comment by kevinpapst** [comment]
This RTL fix is ... WOW 😁 but it seems SASS does not compile these rules properly:
https://rtlcss.com/learn/usage-guide/value-directives/index.html#Tip
https://github.com/quasarframework/quasar/issues/5828

I'll try tomorrow ...

**Pull request merged**
