### PR TITLE
Add cards with rounded corners

### PR DESCRIPTION
**Pull request by enricodias**
Rounded corners are easier on the eyes and takes less cognitive effort to visually process. Some elements needed a few changes to make them work with rounded corners. This PR implements the following:

- Add classes `card-rounded-1` to `card-rounded-4` to control the card border radius
- Add classes `card-edge-right|left-top|bottom` to force square edges (useful for tabs)
- Add new examples to the demo

Some tweaks were made to `card-img`, `card-progress`, `card-status` and `card-stacked` to make them look good with rounded corners. I'm not a frontend developer, but I think the result wasn't that bad:

rounded1

rounded2

### CODE REVIEW

**Comment by codecalm** [comment]
@enricodias thank you for your work! 
but, can you remove changes from `dist` and `demo` folder? It's hard to review 106 files :/

**Comment by enricodias** [comment]
@codecalm sure, I just removed the last commit.

Also, would you be interested in a github action that builds the `dist ` and `demo ` folders automatically in every merge/release?

**Comment by enricodias** [comment]
@codecalm do you intent to accept this contribution? I'm just asking because I'm working on other changes that relies on this PR.

**Review by FreexD — APPROVED** [review]
@enricodias looks great to me! Awesome work :) @codecalm could you take a look as well?

**Comment by kevinpapst** [comment]
Just some feedback from a total stranger: 
Tabler has a unique look & feel and these large rounded corners don't fit. 
Additions like these shouldn't be part of the release, but go into project specific styles.

**Comment by enricodias** [comment]
@kevinpapst I understand your point, but several other UI kits have options to control corners like this. Adding it outside in a custom theme will make it hard to keep it up to date with the original Tabler source since there are several widgets that needs a few tweaks to accommodate this. It just felt better to have this option in Tabler itself.

But since this PR is still not merged after almost a year, I think this feature will not be added. That's totally fine too.

**Comment by codecalm** [comment]
for me better idea is to change css props to variables like:

```
.card {
  --card-radius: #{$card-border-radius};
...
}
```

and if someone need card with "more" radius can create class which ovveride default `border-radius`

**Comment by enricodias** [comment]
> for me better idea is to change css props to variables like:
> 
> ```css-scss
> .card {
>   --card-radius: #{$card-border-radius};
> ...
> }
> ```
> 
> and if someone need card with "more" radius can create class which ovveride default `border-radius`

That's whats I thought at first, but there are several other parts that must be tweaked to make this work. Tabs, card progress, card stack, image and others. Just setting the border will break several cards.

**Comment by codecalm** [comment]
I've added `--tblr-card-border-radius` to card component, co user can change all card variants by style attribute, or custom class :)

**Pull request closed without merging**
