### PR TITLE
Change input icon demo to sun and moon

### PR DESCRIPTION
**Pull request by entoil**
## Description
People are mistaking the "Icons input" demo as "gender input" due to the icons used. This changes the icons from male and female to day and night (#37)

## Screenshots (if appropriate):
Sun and Moon icons

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### CODE REVIEW

**Comment by jamiebuilds** [comment]
I'm not making any mistake about the purpose of the input. I specifically stated that it was a good opportunity to set a good example for the community.

**Comment by jamiebuilds** [comment]
Let's also be clear that this pull request is clearly not motivated by an active desire to improve the project but as a way to deny inclusion to non-cis/binary gendered people. @entoil has not had any public GitHub activity in the past four years, this is not an honest attempt to help users of the project.

This is a violation of the [project's code of conduct](https://github.com/tabler/tabler/blob/dev/CODE_OF_CONDUCT.md) and should be treated as such.

**Comment by entoil** [comment]
This pull request would make the input demo inclusive for all parties.

I knew that I would be attacked if I made this pull request, but I still wanted this generous project to do as well as it could, so that is why I am not using my main account.

I don't believe you should discourage contributions from other developers, just because it is not in line with your beliefs. This is an open source project and we're all working together.

**Comment by jamiebuilds** [comment]
I already opened a pull request making the existing inputs more inclusive. This pull request was made in response to shut down that effort. So now if this pull request is accepted it will act as a signal that the project does not care about inclusion and that the code of conduct is without teeth

**Comment by beeman** [comment]
Thanks for your contribution @entoil. 

I've added the Icon Input example with the sun/moon icons as a second example next to the Gender input.

**Pull request merged**
