### PR TITLE
Fix flashing white when dark theme is enabled

### PR DESCRIPTION
**Pull request by dheineman**
Load the theme code as fast as possible to prevent flashing the light theme before fetching and applying the dark theme from the URL or localstorage.

fixes https://github.com/tabler/tabler/issues/1172

### CODE REVIEW

**Comment by rjd22** [comment]
@dheineman this is great work! I will review it in a few days :)

**Comment by rjd22** [comment]
Works great!

**Comment by gladtoseeugo** [comment]
UNSCRIBE

**Comment by gladtoseeugo** [comment]
UNSCRIBE

**Pull request merged**
